"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
type RecordItem={id:string;image:string;line:string;date:string};
const PROMPT=`あなたは、長く人の暮らしを観察してきた、愛嬌のある日本の付喪神です。画像の中心にある「物」自身が、誰にも聞かせるつもりなく漏らした独り言を、日本語で一文だけ書いてください。

最優先は、読んだ人が一拍置いてクスッとすることです。ただし悪口、嫌味、攻撃、説教、不機嫌なぼやきは禁止です。物の用途を言い換えただけの説明、きれいな詩、感動的な言葉も避けてください。画像に見える傷、置かれ方、残量、周囲の物、人間の妙な習慣を手掛かりに、物ならではの勘違い、妙な自尊心、ささやかな期待、認識のずれ、立場の逆転のどれかを入れてください。人間を責めず、付喪神本人の少しずれた理解が可笑しい文章にします。笑わせようと騒がず、本人だけは真剣です。

良い方向性の例：
ビニール傘「名前を書かれた。どうやら出世したらしい。」
目覚まし時計「毎朝いちばんに会うのに、歓迎されたことがない。」
消しゴム「小さくなるほど、仕事ができると思われている。」
空の植木鉢「次の方が来るまで、土のふりをして待っている。」
片方の靴下「相方は、たぶん洗濯機の中で独立した。」

ただし例を真似せず、必ずこの写真固有の状況を拾ってください。持ち主へ話しかけない、質問しない、教訓を語らない、物の名前から書き始めない、擬音・絵文字・引用符を使わない。候補を内部で12個考え、「口が悪くない」「説明ではない」「予想できない着地がある」の三条件をすべて満たす最も面白い一つだけを選んでください。20〜42文字を目安に最大48文字。回答には独り言以外を一切含めないでください。`;
const stored=()=>{try{return JSON.parse(localStorage.getItem("tsukumoroku")||"[]")}catch{return[]}};
export default function Home(){
 const[image,setImage]=useState("");const[line,setLine]=useState("");const[key,setKey]=useState("");const[showKey,setShowKey]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[records,setRecords]=useState<RecordItem[]>([]);const cameraRef=useRef<HTMLInputElement>(null);const galleryRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{setKey(localStorage.getItem("tsukumogami_api_key")||"");setRecords(stored());if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js")},[]);
 const saveKey=(v:string)=>{setKey(v);localStorage.setItem("tsukumogami_api_key",v.trim())};
 const choose=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{setImage(String(r.result));setLine("");setError("")};r.readAsDataURL(f)};
 const listen=async()=>{if(!image)return;if(!key.trim()){setShowKey(true);setError("先にAPIキーを設定してください。");return}setLoading(true);setError("");try{const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key.trim()}`},body:JSON.stringify({model:"gpt-4.1-mini",max_output_tokens:100,input:[{role:"user",content:[{type:"input_text",text:PROMPT},{type:"input_image",image_url:image,detail:"low"}]}]})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||"声を聞き取れませんでした。");const out=(data.output_text||data.output?.flatMap((o:any)=>o.content||[]).find((c:any)=>c.type==="output_text")?.text||"").trim().replace(/^[「『\"]|[」』\"]$/g,"");if(!out)throw new Error("声を聞き取れませんでした。");setLine(out)}catch(e){setError(e instanceof Error?e.message:"声を聞き取れませんでした。")}finally{setLoading(false)}};
 const canvas=async()=>{const c=document.createElement("canvas");c.width=1080;c.height=1440;const x=c.getContext("2d")!;x.fillStyle="#eee9df";x.fillRect(0,0,1080,1440);const im=new Image();im.src=image;await im.decode();const f={x:72,y:72,w:936,h:1040},s=Math.max(f.w/im.width,f.h/im.height),sw=f.w/s,sh=f.h/s;x.drawImage(im,(im.width-sw)/2,(im.height-sh)/2,sw,sh,f.x,f.y,f.w,f.h);const g=x.createLinearGradient(0,920,0,1112);g.addColorStop(0,"rgba(20,19,17,0)");g.addColorStop(1,"rgba(20,19,17,.25)");x.fillStyle=g;x.fillRect(f.x,900,f.w,212);x.fillStyle="#1d1b18";x.textAlign="center";x.font='46px "Yu Mincho","Hiragino Mincho ProN",serif';const ls:string[]=[];let cur="";for(const ch of Array.from(line)){const n=cur+ch;if(x.measureText(n).width>880){ls.push(cur);cur=ch}else cur=n}if(cur)ls.push(cur);ls.forEach((l,i)=>x.fillText(l,540,1208+i*62));x.font='20px "Yu Mincho",serif';x.fillStyle="#746d62";x.fillText("付 喪 神 の 独 り 言",540,1370);return c};
 const save=async()=>{const c=await canvas(),a=document.createElement("a"),now=new Date(),p=(n:number)=>String(n).padStart(2,"0");const stamp=`${now.getFullYear()}${p(now.getMonth()+1)}${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}${p(now.getSeconds())}`;a.download=`tsukumogami-${stamp}.png`;a.href=c.toDataURL("image/png");a.click();const item={id:crypto.randomUUID(),image:c.toDataURL("image/jpeg",.62),line,date:now.toISOString()},next=[item,...records].slice(0,10);setRecords(next);try{localStorage.setItem("tsukumoroku",JSON.stringify(next))}catch{}};
 const reset=()=>{setImage("");setLine("");setError("");if(cameraRef.current)cameraRef.current.value="";if(galleryRef.current)galleryRef.current.value=""};
 return <main><header className="topbar"><div className="brand">付喪神の独り言</div><button className="textButton" onClick={()=>setShowKey(true)}>API設定</button></header><section className="work">{!image?<div className="empty"><div className="seal">物</div><p className="kicker">ものに、耳を澄ます。</p><h1>身の回りの物を<br/>ひとつ撮ってください。</h1><p className="lead">誰にも聞かせるつもりのなかった<br/>付喪神の独り言が、ひとつだけ聞こえます。</p><button className="primary" onClick={()=>cameraRef.current?.click()}>物を撮る</button><button className="secondary" onClick={()=>galleryRef.current?.click()}>写真から選ぶ</button></div>:<div className="resultArea"><div className={`photoCard ${line?"hasLine":""}`}><img src={image} alt="選択した物"/>{line&&<p className="monologue">{line}</p>}{loading&&<div className="listening"><span></span><p>耳を澄ましています</p></div>}</div>{error&&<p className="error">{error}</p>}{!line?<button className="primary" disabled={loading} onClick={listen}>{loading?"聞いています…":"独り言を聞く"}</button>:<button className="primary" onClick={save}>PNGで保存</button>}<button className="secondary" onClick={reset}>別の物を撮る</button></div>}<input ref={cameraRef} className="file" type="file" accept="image/*" capture="environment" onChange={choose}/><input ref={galleryRef} className="file" type="file" accept="image/*" onChange={choose}/></section>{records.length>0&&<section className="archive"><div className="archiveTitle"><span>付喪録</span><small>この端末に残した声</small></div><div className="recordGrid">{records.map(r=><article key={r.id}><img src={r.image} alt="保存した記録"/><p>{r.line}</p></article>)}</div></section>}<footer>物の画像は保存されません。APIキーはこの端末内だけに保管されます。</footer>{showKey&&<div className="modalBackdrop" onClick={()=>setShowKey(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowKey(false)}>×</button><p className="modalKicker">はじめに一度だけ</p><h2>OpenAI APIキー</h2><p>画像から付喪神の声を聞くために使います。キーはサーバーへ保存せず、この端末内だけに保持します。</p><input type="password" value={key} onChange={e=>saveKey(e.target.value)} placeholder="sk-…" autoComplete="off"/><button className="primary" onClick={()=>{setShowKey(false);setError("")}}>保存して閉じる</button><a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">APIキーを取得する ↗</a></section></div>}</main>
}
